name: infy_vcard
description: A new Flutter project.

# La siguiente línea previene que el paquete se publique accidentalmente en pub.dev
publish_to: 'none' # Eliminar esta línea si deseas publicarlo en pub.dev

# Versión de la aplicación
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Dependencias del proyecto
  app_settings: ^5.1.1
  auto_size_text: 3.0.0
  collection: 1.18.0
  country_code_picker: ^3.0.0
  equatable: 2.0.5
  fl_chart: ^0.66.2
  flutter_barcode_scanner: 
    git:
      url: https://github.com/FlutterFlow/flutter_barcode_scanner
  flutter_contacts: ^1.1.6
  flutter_keyboard_visibility: 5.2.0
  flutter_spinkit: 5.2.0
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  go_router: 7.1.1
  google_fonts: 6.1.0
  http: ^1.2.0
  image: ^4.1.7
  image_picker: ^1.0.4
  json_path: 0.6.2
  mime_type: 1.0.0
  nfc_manager: ^3.3.0
  page_transition: 2.1.0
  path_provider: 2.0.14
  provider: 6.0.5
  qr_image: ^1.0.0
  share_plus: 7.2.1
  shared_preferences: 2.2.2
  sqflite: 2.2.6
  timeago: 3.2.2
  url_launcher: 6.1.10
  video_player: 2.8.1
  flutter_cache_manager: 3.3.1
  expandable: 5.0.1
  quill_html_editor: ^2.2.7
  tutorial_coach_mark: ^1.2.11

  # Iconos de estilo iOS
  cupertino_icons: ^1.0.0
  intl: ^0.19.0
  file_picker: ^6.2.1

dependency_overrides:
  http: ^1.2.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 3.0.0
  lints: 3.0.0

  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'

flutter:

  # Asegura que los iconos de Material Icons estén incluidos
  uses-material-design: true

  # Agregar recursos al proyecto
  assets:
    - assets/images/

  # Fuentes personalizadas (descomentar y modificar si es necesario)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
